# adapted from http://conda.pydata.org/docs/travis.html
language: python
python:
 # We don't actually use the Travis Python, but this keeps it organized.
 - "2.7"
 - "3.5"

# switch to new infrastructure
sudo: false

before_install:
 # download and install miniconda
 - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/conda
 - export PATH="$HOME/conda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda

 # install essentials for deployment
 - conda install -q conda-build
 - conda install -q anaconda-client

 # Useful for debugging any issues with conda
 - conda info -a

 # create and activate the build/test environment
 - conda create -q -n tenv python=$TRAVIS_PYTHON_VERSION pip cmake
 - source activate tenv

 # Upgrade pip
 - python -m pip install --upgrade pip

install:
 # Necessary dependencies
 - conda install -q tqdm numpy pytest pyqt
 - conda install -c conda-forge umap-learn
 - conda install -c ambermd pytraj
 - conda install -c omnia mdtraj
 - python -m pip install prody biopython seaborn sklearn scipy==1.1.0 mordred nltk xgboost requests chembl_webresource_client matplotlib
 - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install --force-reinstall gevent==1.2.2 greenlet==0.4.12; fi;

 # Install the most recent rdkit package from the RDKit anaconda channel.
 - conda install -q -c rdkit rdkit


before_script:
 # RDKit
 - export RDBASE=$CONDA_PREFIX/Library/share/RDKit
 - echo $RDBASE

script:
 # Run tests
 - python -m pytest tests/ -k 'test_docking or test_dude'

before_deploy:
 - conda install -f  setuptools
 - conda build conda_recipe -c local

deploy:
  # Deploy to Anaconda.org
    provider: script
    script: anaconda -t $CONDA_UPLOAD_TOKEN  upload  --skip -u NostrumBioDiscovery $HOME/conda/conda-bld/**/modtox*.tar.bz2
    skip_cleanup: true
    on:
tags: true

